version: 2

gomod:
  proxy: true

builds:
  - main: ./cmd/seek
    binary: seek
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  disable: "true"

release:
  mode: keep-existing
  extra_files:
    - glob: sbom.cyclonedx.json
