package main

import (
	"bytes"
	"errors"
	"reflect"
	"testing"

	ctags "github.com/sourcegraph/go-ctags"
)

func TestExtractSemanticUnitsCoversSymbolsAndGaps(t *testing.T) {
	content := []byte("package sample\n\n// Alpha docs\nfunc Alpha() {}\n\nfunc Beta() {}\n")
	entries := []*ctags.Entry{
		{Name: "Beta", Line: 6, Language: "Go"},
		{Name: "Alpha", Line: 4, Language: "Go"},
		// The stable first entry at one line wins.
		{Name: "Zeta", Line: 4, Language: "Go"},
		{Name: "bad-low", Line: 0},
		{Name: "bad-high", Line: 99},
	}
	units := extractSemanticUnits("sample.go", content, entries, nil)
	if len(units) != 3 {
		t.Fatalf("units=%d, want 3", len(units))
	}
	want := []struct {
		kind   semanticUnitKind
		start  uint64
		end    uint64
		symbol string
	}{
		{kind: semanticUnitGap, start: 0, end: 30},
		{kind: semanticUnitSymbol, start: 30, end: 47, symbol: "Alpha"},
		{kind: semanticUnitSymbol, start: 47, end: 62, symbol: "Beta"},
	}
	for index, expected := range want {
		unit := units[index]
		if unit.kind != expected.kind || unit.start != expected.start || unit.end != expected.end ||
			unit.symbol != expected.symbol || !bytes.Equal(unit.text, content[expected.start:expected.end]) {
			t.Fatalf("unit %d=%+v, want %+v", index, unit, expected)
		}
	}
	for _, unit := range units {
		if unit.parserResult != semanticParserCTags {
			t.Fatalf("parser result=%d, want ctags", unit.parserResult)
		}
	}
}

func TestExtractSemanticUnitsFallbacks(t *testing.T) {
	tests := []struct {
		name       string
		content    []byte
		parseErr   error
		wantResult semanticParserResult
	}{
		{name: "no symbols", content: []byte("plain text\n"), wantResult: semanticParserNoSymbols},
		{name: "parser failed", content: []byte("func F() {}\n"), parseErr: errors.New("ctags stopped"), wantResult: semanticParserFailed},
		{name: "invalid UTF-8", content: []byte{'a', 0xff, 'b'}, wantResult: semanticParserInvalidUTF8},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			units := extractSemanticUnits("input", test.content, nil, test.parseErr)
			if len(units) != 1 || units[0].kind != semanticUnitFallback ||
				units[0].parserResult != test.wantResult || units[0].start != 0 ||
				units[0].end != uint64(len(test.content)) ||
				!bytes.Equal(units[0].text, test.content) {
				t.Fatalf("units=%+v", units)
			}
		})
	}
}

func TestExtractSemanticUnitsSkipsBinaryContent(t *testing.T) {
	content := []byte{'p', 'n', 'g', 0, 1, 2, 3}
	units := extractSemanticUnits("image.bin", content, nil, errors.New("ctags failed"))
	if len(units) != 0 {
		t.Fatalf("units=%d, want explicit binary skip", len(units))
	}
}

func TestExtractSemanticUnitsSkipsMarkedGeneratedSource(t *testing.T) {
	content := []byte("// Code generated by fixture. DO NOT EDIT.\npackage generated\n")
	if !semanticContentIsGenerated(content) {
		t.Fatal("standard generated-source marker was not recognized")
	}
	units := extractSemanticUnits("generated.go", content, nil, nil)
	if len(units) != 0 {
		t.Fatalf("units=%d, want explicit generated-source skip", len(units))
	}
	for _, source := range [][]byte{
		[]byte("// Code generated examples are documented here.\n"),
		[]byte("// generated by fixture; do not edit\n"),
		append(bytes.Repeat([]byte{' '}, 4096), []byte("// Code generated late. DO NOT EDIT.\n")...),
	} {
		if semanticContentIsGenerated(source) {
			t.Fatalf("non-standard marker was accepted: %q", source[:min(len(source), 80)])
		}
	}
}

func TestExtractSemanticUnitsRejectsPartialParserOutput(t *testing.T) {
	content := []byte("header\nfunc F() {}\n")
	entries := []*ctags.Entry{{Name: "F", Kind: "function", Line: 2}}
	for _, test := range []struct {
		name    string
		content []byte
		err     error
		want    semanticParserResult
	}{
		{name: "parse error", content: content, err: errors.New("partial output"), want: semanticParserFailed},
		{name: "invalid UTF-8", content: append(append([]byte(nil), content...), 0xff), want: semanticParserInvalidUTF8},
	} {
		t.Run(test.name, func(t *testing.T) {
			units := extractSemanticUnits("input.go", test.content, entries, test.err)
			if len(units) != 1 || units[0].kind != semanticUnitFallback ||
				units[0].parserResult != test.want || units[0].symbol != "" ||
				units[0].start != 0 || units[0].end != uint64(len(test.content)) ||
				!bytes.Equal(units[0].text, test.content) {
				t.Fatalf("units=%+v", units)
			}
		})
	}
}

func TestSemanticSymbolMetadataKeepsCtagsContext(t *testing.T) {
	entry := &ctags.Entry{
		Name:       "ServeHTTP",
		Kind:       "method",
		Parent:     "Server",
		ParentKind: "type",
		Signature:  "(w, r)",
	}
	if got, want := semanticSymbolMetadata(entry), "type Server method ServeHTTP (w, r)"; got != want {
		t.Fatalf("metadata=%q, want %q", got, want)
	}
}

func TestExtractSemanticUnitsSplitsLargeLines(t *testing.T) {
	content := bytes.Repeat([]byte{'x'}, semanticUnitMaxBytes*2+17)
	units := extractSemanticUnits("large.txt", content, nil, nil)
	if len(units) != 3 {
		t.Fatalf("units=%d, want 3", len(units))
	}
	for index, unit := range units {
		if len(unit.text) > semanticUnitMaxBytes {
			t.Fatalf("unit bytes=%d, limit=%d", len(unit.text), semanticUnitMaxBytes)
		}
		wantStart := index * semanticUnitMaxBytes
		wantEnd := min(wantStart+semanticUnitMaxBytes, len(content))
		if unit.start != uint64(wantStart) || unit.end != uint64(wantEnd) ||
			!bytes.Equal(unit.text, content[wantStart:wantEnd]) {
			t.Fatalf("unit %d spans %d:%d, want %d:%d", index, unit.start, unit.end, wantStart, wantEnd)
		}
	}
}

func TestExtractSemanticUnitsIsDeterministic(t *testing.T) {
	content := []byte("header\nfunc Z() {}\nfunc A() {}\n")
	left := []*ctags.Entry{{Name: "A", Line: 3}, {Name: "Z", Line: 2}}
	right := []*ctags.Entry{{Name: "Z", Line: 2}, {Name: "A", Line: 3}}
	first := extractSemanticUnits("x.go", content, left, nil)
	second := extractSemanticUnits("x.go", content, right, nil)
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("entry order changed units:\nfirst=%+v\nsecond=%+v", first, second)
	}
}
